services:
  n8n:
    image: n8nio/n8n:2.10.4
    container_name: n8n_pi_automate
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      - N8N_RUNNERS_MODE=external
      - N8N_RUNNERS_BROKER_LISTEN_ADDRESS=0.0.0.0
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./workflows:/home/node/workflows
      - ./scripts:/home/node/scripts
    networks:
      - n8n-network

  n8n-python-runner:
    image: n8nio/runners:2.10.4
    container_name: n8n_worker
    restart: unless-stopped
    environment:
      - N8N_RUNNERS_TASK_BROKER_URI=http://n8n_pi_automate:5679
    env_file:
      - .env
    networks:
      - n8n-network
    depends_on:
      - n8n

  speaches:
    image: ghcr.io/speaches-ai/speaches:0.9.0-rc.3-cpu
    container_name: whisper_api
    restart: unless-stopped
    ports:
      - "8888:8000"
    environment:
      - PRELOAD_MODELS=["Systran/faster-whisper-small"]
      - WHISPER__COMPUTE_TYPE=int8
      - HOST=0.0.0.0
    volumes:
      - ./whisper_models:/root/.cache/huggingface
    networks:
      - n8n-network

  ngrok:
      image: ngrok/ngrok:latest
      container_name: ngrok_tunnel
      restart: unless-stopped
      env_file:
        - .env
      command: http --domain=${NGROK_DOMAIN} n8n_pi_automate:5678
      networks:
        - n8n-network

networks:
  n8n-network:
    driver: bridge